namespace Beskar.CodeAnalytics.Data.Enums.Syntax;

public enum SyntaxColor : ushort
{
   Comment = 1,
   ExcludedCode = 2,
   Identifier = 3,
   Keyword = 4,
   ControlKeyword = 5,
   NumericLiteral = 6,
   Operator = 7,
   OperatorOverloaded = 8,
   PreprocessorKeyword = 9,
   StringLiteral = 10,
   WhiteSpace = 11,
   Text = 12,
   ReassignedVariable = 13,
   ObsoleteSymbol = 14,
   StaticSymbol = 15,
   PreprocessorText = 16,
   Punctuation = 17,
   VerbatimStringLiteral = 18,
   StringEscapeCharacter = 19,
   
   ClassName = 20,
   RecordClassName = 21,
   DelegateName = 22,
   EnumName = 23,
   InterfaceName = 24,
   ModuleName = 25,
   StructName = 26,
   RecordStructName = 27,
   TypeParameterName = 28,
   FieldName = 29,
   EnumMemberName = 30,
   ConstantName = 31,
   LocalName = 32,
   ParameterName = 33,
   MethodName = 34,
   ExtensionMethodName = 35,
   PropertyName = 36,
   EventName = 37,
   NamespaceName = 38,
   LabelName = 39,
   
   XmlDocCommentAttributeName = 40,
   XmlDocCommentAttributeQuotes = 41,
   XmlDocCommentAttributeValue = 42,
   XmlDocCommentCDataSection = 43,
   XmlDocCommentComment = 44,
   XmlDocCommentDelimiter = 45,
   XmlDocCommentEntityReference = 46,
   XmlDocCommentName = 47,
   XmlDocCommentProcessingInstruction = 48,
   XmlDocCommentText = 49,
   
   XmlLiteralAttributeName = 50,
   XmlLiteralAttributeQuotes = 51,
   XmlLiteralAttributeValue = 52,
   XmlLiteralCDataSection = 53,
   XmlLiteralComment = 54,
   XmlLiteralDelimiter = 55,
   XmlLiteralEmbeddedExpression = 56,
   XmlLiteralEntityReference = 57,
   XmlLiteralName = 58,
   XmlLiteralProcessingInstruction = 59,
   XmlLiteralText = 60,
   
   RegexComment = 61,
   RegexCharacterClass = 62,
   RegexAnchor = 63,
   RegexQuantifier = 64,
   RegexGrouping = 65,
   RegexAlternation = 66,
   RegexText = 67,
   RegexSelfEscapedCharacter = 68,
   RegexOtherEscape = 69,
   
   Default = 70
}