namespace Beskar.CodeAnalytics.Data.Enums.Symbols;

public enum SpecialTypeKind : byte
{
   None = 0,
   SystemObject = 1,
   SystemEnum = 2,
   SystemMulticastDelegate = 3,
   SystemDelegate = 4,
   SystemValueType = 5,
   SystemVoid = 6,
   SystemBoolean = 7,
   SystemChar = 8,
   SystemSByte = 9,
   SystemByte = 10,
   SystemInt16 = 11,
   SystemUInt16 = 12,
   SystemInt32 = 13,
   SystemUInt32 = 14,
   SystemInt64 = 15,
   SystemUInt64 = 16,
   SystemDecimal = 17,
   SystemSingle = 18,
   SystemDouble = 19,
   SystemString = 20,
   SystemIntPtr = 21,
   SystemUIntPtr = 22,
   SystemArray = 23,
   SystemCollectionsIEnumerable = 24,
   SystemCollectionsGenericIEnumerableT = 25,
   SystemCollectionsGenericIListT = 26,
   SystemCollectionsGenericICollectionT = 27,
   SystemCollectionsIEnumerator = 28,
   SystemCollectionsGenericIEnumeratorT = 29,
   SystemCollectionsGenericIReadOnlyListT = 30,
   SystemCollectionsGenericIReadOnlyCollectionT = 31,
   SystemNullableT = 32,
   SystemDateTime = 33,
   SystemRuntimeCompilerServicesIsVolatile = 34,
   SystemIDisposable = 35,
   SystemTypedReference = 36,
   SystemArgIterator = 37,
   SystemRuntimeArgumentHandle = 38,
   SystemRuntimeFieldHandle = 39,
   SystemRuntimeMethodHandle = 40,
   SystemRuntimeTypeHandle = 41,
   SystemIAsyncResult = 42,
   SystemAsyncCallback = 43,
   SystemRuntimeCompilerServicesRuntimeFeature = 44,
   SystemRuntimeCompilerServicesPreserveBaseOverridesAttribute = 45,
   Count = 46,
   SystemRuntimeCompilerServicesInlineArrayAttribute = Count
}